default:
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -f dockerfile.dev -t $CI_REGISTRY_IMAGE:$TAG_TEST .
    - docker push $CI_REGISTRY_IMAGE:$TAG_TEST
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && 
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

test:
  stage: test
  needs: ["build"]
  script:
    - docker pull $CI_REGISTRY_IMAGE:$TAG_TEST
    - docker run --rm $CI_REGISTRY_IMAGE:$TAG_TEST npm run test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && 
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

deploy:
  stage: deploy
  script:
    - docker build -f dockerfile.prod -t $CI_REGISTRY_IMAGE:$TAG_PROD .
    - docker push $CI_REGISTRY_IMAGE:$TAG_PROD
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual